name: Docker Image CI

env:
  DOCKER_ORGANISATION_NAME: wseresearch
  DOCKER_IMAGE_NAME: fake-question-answering-system

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Some Test
        run: ls -all
      - name: Some Test
        run: cat service_config/files/template.env
      - name: Some Test
        run: cat service_config/files/template.env>service_config/files/.env
      - name: Some Test
        run: cat service_config/files/template.env
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Get current version from pom.xml
        run: echo "X_DOCKER_IMAGE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Build the Docker image
        run: bash -c ./service_config/build_image.sh
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push latest docker image
        run: docker push $DOCKER_ORGANISATION_NAME/$DOCKER_IMAGE_NAME:latest
      - name: Push docker image version
        run: docker push "$DOCKER_ORGANISATION_NAME/$DOCKER_IMAGE_NAME:$X_DOCKER_IMAGE_VERSION"
      - name: Init update
        uses: WSE-research/docker-service-updater@v0.2.0
        with:
          updater_host: ${{ secrets.UPDATER_HOST }}
          api_key: ${{ secrets.API_KEY }}